#pragma once

//WORLD SETTINGS
#define WORLDWIDTH 20
#define WORLDHEIGHT 20

//player
#define HUMANSTR 5
#define HUMANINITIATIVE 4
#define HUMANABILITYCOOLDOWN 5
#define HUMANCHAR 'H'
#define HUMANSTARTINGX 1
#define HUMANSTARTINGY 1
#define HUMANFULLNAME "HUMAN"

//wolf
#define WOLFINITIATIVE 5
#define WOLFSTR 9
#define WOLFCHAR 'W'
#define WOLFFULLNAME "WOLF"

//sheep
#define SHEEPINITIATIVE 4
#define SHEEPSTR 4
#define SHEEPCHAR 'S'
#define SHEEPFULLNAME "SHEEP"

//FOX
#define FOXINITIATIVE 7
#define FOXSTR 3
#define FOXCHAR 'F'
#define FOXFULLNAME "FOX"

//antelope
#define ANTELOPEINITIATIVE 5
#define ANTELOPESTR 4
#define ANTELOPECHAR 'A'
#define ANTELOPEFULLNAME "ANTELOPE"

//turtle
#define TURTLEINITIATIVE 1
#define TURTLESTR 2
#define TURTLECHAR 'T'
#define TURTLEFULLNAME "TURTLE"
#define TURTLEDEFLECTIONTRESHOLD 5

//grass
#define GRASSSTR 0
#define GRASSCHAR 'G'
#define GRASSFULLNAME "GRASS"

//pineborsch
#define PINEBORSCHSTR 10
#define PINEBORSCHCHAR 'P'
#define PINEBORSCHFULLNAME "PINE BORSCH"

//nightshade
#define NIGHTSHADESTR 99
#define NIGHTSHADECHAR 'N'
#define NIGHTSHADEFULLNAME "NIGHTSHADE"

//dandelion
#define DANDELIONSTR 0
#define DANDELIONCHAR 'D'
#define DANDELIONFULLNAME "DANDELION"

//guarana
#define GUARANASTR 0
#define GUARANACHAR 'G'
#define GUARANAFULLNAME "GUARANA"
