#pragma once

//WORLD SETTINGS
#define WORLDWIDTH 20
#define WORLDHEIGHT 20

#define HUMANSTR 5
#define HUMANINITIATIVE 4
#define HUMANABILITYCOOLDOWN 5
#define HUMANCHAR 'H'
#define HUMANSTARTINGX 1
#define HUMANSTARTINGY 1

#define FOXINITIATIVE 10
